import { clientsClaim } from 'workbox-core';
import {
  addPlugins,
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
  precacheAndRoute,
} from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { RangeRequestsPlugin } from 'workbox-range-requests';
import { CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

self.skipWaiting();
clientsClaim();

// Add RangeRequestsPlugin to precached assets so that all precached audio files
// return HTTP 206 Partial Content when requested with Range headers (required for iOS Safari and scrubbing).
addPlugins([new RangeRequestsPlugin()]);

// Precache all assets generated by Vite build (HTML, JS, CSS, icons, and all 91 audio files).
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Fallback runtime caching route for any audio requests (both local and remote)
registerRoute(
  ({ request, url }) => request.destination === 'audio' || url.pathname.endsWith('.mp3'),
  new CacheFirst({
    cacheName: 'audio-cache',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new RangeRequestsPlugin(),
    ],
  }),
);

// SPA navigation route: map all navigation requests (e.g. /ruqyah/1) to index.html
registerRoute(new NavigationRoute(createHandlerBoundToURL('index.html')));
